name: Upload via SFTP

on:
  push:
    branches:
      - fip

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Upload via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            server: ${{ secrets.SFTP_SERVER }}
            username: ${{ secrets.SFTP_USERNAME }}
            password: ${{ secrets.SFTP_PASSWORD }}
            port: ${{ secrets.SFTP_PORT }}
            local_path: './build/*'
            remote_path: '/public_html/fip/page-generator'
            sftp_only: true
